apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^login$', views.login, name='do_the_login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^register$', views.register),
    url(r'^success$', views.success),
]

apps/wishlist/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^dashboard$', views.dashboard, name='dashboard'),
    url(r'^wish_items/create$', views.create, name='create'),
    url(r'^wish_items/add$', views.add, name='add'),
    url(r'^wish_items/(?P<item_id>\d+)$', views.display, name='display'),
    url(r'^wish_items/(?P<item_id>\d+)/add$', views.item_add),
    url(r'^wish_items/(?P<item_id>\d+)/remove$', views.remove),
    url(r'^wish_items/(?P<item_id>\d+)/delete$', views.delete),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.wishlist.urls', namespace='wishlist')),
    url(r'^login/', include('apps.login.urls', namespace='login')),
]

apps/login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import re
import bcrypt
from django.db import models
from datetime import datetime

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
NAME_REGEX = re.compile(r'^[A-Za-z]\w+$')

class UserManager(models.Manager):
    def validate_login(self, post_data):
        errors = []
        # check DB for post_data['email']
        if len(self.filter(email=post_data['email'])) > 0:
            # check this user's password
            user = self.filter(email=post_data['email'])[0]
            if not bcrypt.checkpw(post_data['password'].encode(), user.password.encode()):
                errors.append('email/password incorrect')
        else:
            errors.append('email/password incorrect')

        if errors:
            return errors
        return user

    # def books_reviewed(self):
    #     return self.model.reviews_left.all().values('book').distict()

    def validate_registration(self, post_data):
        errors = []
        # check length of name fields
        if len(post_data['name']) < 2 or len(post_data['alias']) < 2:
            errors.append("name fields must be at least 3 characters")
        # check length of name password
        if len(post_data['password']) < 8:
            errors.append("password must be at least 8 characters")
        # check name fields for letter characters            
        if not re.match(NAME_REGEX, post_data['name']):
            errors.append('name fields must be letter characters only')
        # check emailness of email
        if not re.match(EMAIL_REGEX, post_data['email']):
            errors.append("invalid email")
        # check uniqueness of email
        if len(User.objects.filter(email=post_data['email'])) > 0:
            errors.append("email already in use")
        # check password == password_confirm
        if post_data['password'] != post_data['password_confirm']:
            errors.append("passwords do not match")

        if not errors:
            # make our new user
            # hash password
            hashed = bcrypt.hashpw((post_data['password'].encode()), bcrypt.gensalt(5))

            new_user = self.create(
                name=post_data['name'],
                alias=post_data['alias'],
                email=post_data['email'],
                password=hashed
            )
            return new_user
        return errors


class User(models.Model):
    name = models.CharField(max_length=100)
    alias = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    date_hired = models.DateField(default = datetime.now)
    objects = UserManager()
    def __str__(self):
        return self.email

apps/wishlist/models.py
from __future__ import unicode_literals
import re
import bcrypt
from django.db import models
from datetime import datetime
from ..login.models import User

class ItemManager(models.Manager):
    def validate_item(self, post_data, added_by):
        errors = []
        if len(post_data['item_name']) < 4:
            errors.append("item name must be at least 3 characters")
        if not errors:
            new_item = self.create(
                added_by = added_by.name,
                name = post_data["item_name"]
                )
            new_item.wished_by.add(added_by)
            return new_item
        return errors


class Item(models.Model):
    name = models.CharField(max_length=100)
    added_by = models.CharField(max_length=100)
    date_added = models.DateField(default = datetime.now)
    # https://docs.djangoproject.com/en/2.0/topics/db/examples/many_to_many/
    objects = ItemManager()
    wished_by = models.ManyToManyField(User, blank = True)
    


apps/login/views.py

# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import User
from django.shortcuts import render, redirect, HttpResponseRedirect, reverse
from django.contrib import messages

# Create your views here.
def index(request):
    return render(request, 'login/index.html')

def register(request):
    result = User.objects.validate_registration(request.POST)
    if type(result) == list:
        for err in result:
            messages.error(request, err)
        return redirect('/')
    request.session['user_id'] = result.id
    messages.success(request, "Successfully registered!")
    return HttpResponseRedirect(reverse("wishlist:index"))

def login(request):
    result = User.objects.validate_login(request.POST)
    if type(result) == list:
        for err in result:
            messages.error(request, err)
        return redirect('/')
    request.session['user_id'] = result.id
    messages.success(request, "Successfully logged in!")
    return HttpResponseRedirect(reverse("wishlist:dashboard"))

def logout(request):
    for key in request.session.keys():
        del request.session[key]
    return redirect('/')

def success(request):
    try:
        request.session['user_id']
    except KeyError:
        return redirect('/')
    context = {
        'user': User.objects.get(id=request.session['user_id'])
    }
    return render(request, 'login/success.html', context)

apps/wishlist/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse
from ..login.models import User
from .models import Item
from django.contrib import messages


# Create your views here.


def index(request):
    context = {
        "message" : "test shit",
    }
    return render(request, "index.html", context)

def dashboard(request):
    current_user = User.objects.get(id=request.session['user_id'])
    context = {
        "user" : current_user,
        "wish_list_items" : current_user.item_set.all(),
        # https://stackoverflow.com/questions/35012942/related-field-got-invalid-lookup-icontains/35013091
        "non_wish_items" : Item.objects.exclude(wished_by__name__icontains = current_user.name)
    }
    return render(request, "dashboard.html", context)

def create(request):
    return render(request, "create.html")

def add(request):
    added_by = User.objects.get(id=request.session['user_id'])
    result = Item.objects.validate_item(request.POST, added_by)
    if type(result) == list:
        for err in result:
            messages.error(request, err)
        return redirect('/wish_items/create')
    return redirect('/dashboard')

def display(request, item_id):
    current_item = Item.objects.get(id = item_id)
    context = {
        "people" : Item.objects.get(id = item_id).wished_by.all(),
        "item" : current_item
    }
    return render(request, "display.html", context)

def item_add(request, item_id):
    current_user = User.objects.get(id=request.session['user_id'])
    current_item = Item.objects.get(id = item_id)
    current_item.wished_by.add(current_user)
    return redirect('/dashboard')

   

def remove(request, item_id):
    current_user = User.objects.get(id=request.session['user_id'])
    current_item = Item.objects.get(id = item_id)
    current_item.wished_by.remove(current_user)
    return redirect('/dashboard')

def delete(request, item_id): 
    current_item = Item.objects.get(id = item_id)
    current_item.delete()
    return redirect('/dashboard')

apps/login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p class="{{ message.tags }}">{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}
        <h1>Welcome</h1>
        <h2>Registration</h2>
        <form action="/login/register" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name">
            </div>
            <div class="form-group">
                <label for="alias">Alias</label>
                <input type="text" name="alias">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password">
            </div>
            <div class="form-group">
                <label for="password_confirm">Confirm Password</label>
                <input type="password" name="password_confirm">
            </div>
            <div class="form-group">
                    <label for="date_hired">Date Hired</label>
                    <input type="date" name="date_hired">
                </div>
            <input type="submit" value='Register'>
        </form>
        <h2>Login</h2>
        <form action="{% url 'login:do_the_login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password">
            </div>
            <input type="submit" value='Login'>
        </form>
    </body>
</html>

apps/login/templates/login/show.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link href="{% static 'login/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <p><a href="/books">Home</a> | <a href="{% url 'review:add' %}">Add book and review</a> | <a href="/logout">Logout</a></p>
        <h1><strong>User Alias: </strong>{{user.alias}}</h1>
        <h2><strong>Name: </strong> {{user.name}}</h2> 
        <h2><strong>Email: </strong> {{user.email}}</h2> 
        <h2><strong>Total Reviews: </strong> {{user.reviews_left.all.count}}</h2>
        <hr>
        <h1>Posted Reviews on the Folowing Books</h1>
        {% for book in unique_book_reviews %}
        <h3><a href="/books/{{book.id}}">{{book.title}}</a></h3>
        {% endfor %}
    </body>
</html>

apps/login/templates/login/success.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>Success! Welcome, {{ user.first_name }}</h1>
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}
    </body>
</html>

apps/wishlist/templates/create.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Create Item</title>    
    </head>
  <body>
        <p style = "float:right"><a href="/dashboard">home</a> <a href="#" >logout</a></p>
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p class="{{ message.tags }}">{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}
      <h1>Create a Wish List Item!</h1>
      <form action="add" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="item_name">Name</label>
            <input type="text" name="item_name">
        </div>
        <input type="submit" value='Add'>
    </form>
  </body>
</html>

apps/wishlist/templates/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>   
    </head>
  <body>
      <a href="/login/logout" style = "float:right">logout</a>
      <h1>Hello {{user.name}}!</h1>
      <p>Your wishlist:</p>
        <table>
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Added By</th>
                    <th>Date Added</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                    {% for item in wish_list_items %}
                    <tr>
                        <td><a href = "/wish_items/{{item.id}}">{{item.name}}</a></td>
                        <td>{{item.added_by}}</td>
                        <td>{{item.date_added}}</td>
                        {% if item.added_by == user.name %}
                        <td><a href = "/wish_items/{{item.id}}/delete">Delete</a></td>
                        {% else %}
                        <td><a href = "/wish_items/{{item.id}}/remove">Remove from Wishlist</a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
            </tbody>
        </table>

        <h2>Other user's wish items</h2>
        <table>
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Added By</th>
                        <th>Date Added</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                        {% for item in non_wish_items %}
                        <tr>
                            <td>{{item.name}}</td>
                            <td>{{item.added_by}}</td>
                            <td>{{item.date_added}}</td>
                            <td><a href = "/wish_items/{{item.id}}/add">Add Item to Wishlist</a></td>
                        </tr>
                        {% endfor %}
                </tbody>
            </table>
      <a href="wish_items/create" style = "float:right">Create Item</a>
  </body>
</html>

apps/wishlist/templates/display.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Product Page</title>   
    </head>
  <body>
        <p style = "float:right"><a href="/dashboard">home</a> <a href="#" >logout</a></p>
      <h1>{{item.name}}</h1>
      <h3>Users that have added that item under their wish list</h3>
      {% for person in people %}
       <p>{{person.name}}</p>
        {% endfor %}
  </body>
</html>

apps/wishlist/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Login</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p class="{{ message.tags }}">{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}
        <h1>Welcome</h1>
        <h2>Registration</h2>
        <form action="/login/register" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name">
            </div>
            <div class="form-group">
                <label for="alias">Alias</label>
                <input type="text" name="alias">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password">
            </div>
            <div class="form-group">
                <label for="password_confirm">Confirm Password</label>
                <input type="password" name="password_confirm">
            </div>
            <div class="form-group">
                    <label for="date_hired">Date Hired</label>
                    <input type="date" name="date_hired">
            </div>
            <input type="submit" value='Register'>
        </form>
        <h2>Login</h2>
        <form action="{% url 'login:do_the_login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password">
            </div>
            <input type="submit" value='Login'>
        </form>
    </body>
</html>